#!/usr/bin/env python3
"""Is a load_table gap the client, or a different request?

    $ python3 bench_delegation.py --only microsoft-onelake --iters 40
    wrote evidence/bench-delegation-microsoft-onelake-<ts>.txt

pyiceberg sets `X-Iceberg-Access-Delegation: vended-credentials` on its session
by default (catalog/rest/__init__.py:881). iceberg-catalog-rest 0.10.1 sends no
such header. So on load_table the two clients do not ask a catalog the same
question, and a catalog that does work to vend credentials is timed doing it
for one client only. A ratio across that is not a client comparison.

MEASURED 2026-09-18: OneLake load_table read 36.6 ms p50 in Rust against
159.2 ms in pyiceberg, 4.35x, while its five other operations sat at 0.99 to
1.02. This takes the one request apart: the same URL on the same session, with
the header and without it, then parsed, then the whole client method, then the
whole method with the header removed. Interleaved, one iteration of each in
turn, for the reason bench_breakdown.py is.

Nothing from the response reaches disk except its size and the NAMES of the
top-level and config keys, because a loadTable response can carry live storage
credentials.
"""

import argparse
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
CONF = os.path.join(HERE, os.pardir, "iceberg-conformance")
sys.path.insert(0, HERE)
sys.path.insert(0, CONF)

import yaml                                          # noqa: E402
import pyiceberg                                     # noqa: E402
import redact                                        # noqa: E402
import run_pyiceberg as rp                           # noqa: E402
from bench_breakdown import timed_interleaved, us, sem_us, p50_diff_interval  # noqa: E402
from pyiceberg.catalog.rest import Endpoints, RestCatalog, TableResponse  # noqa: E402

HEADER = "X-Iceberg-Access-Delegation"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default="apache-polaris")
    ap.add_argument("--iters", type=int, default=40)
    args = ap.parse_args()

    cfg = yaml.safe_load(open(os.path.join(CONF, "catalogs.yaml")))
    cat = next(c for c in cfg["catalogs"] if c["name"] == args.only)
    mode, _ = rp.auth_plan(cat.get("auth"))
    catalog = RestCatalog(cat["name"], **rp.base_props(cat, mode))
    session = catalog._session
    sent = session.headers.get(HEADER)

    ident = tuple(cat["namespace"].split(".")) + (cat["table"],)
    # The URL the method builds, so every layer is the same request.
    url = catalog.url(Endpoints.load_table, prefixed=True,
                      **catalog._split_identifier_for_path(ident))

    def without_header(fn):
        def run():
            saved = session.headers.pop(HEADER, None)
            try:
                return fn()
            finally:
                if saved is not None:
                    session.headers[HEADER] = saved
        return run

    def ok_text(response):
        if response.status_code != 200:
            raise RuntimeError("HTTP %d from the catalog; refusing to time it"
                               % response.status_code)
        return response.text

    def shape(text):
        body = json.loads(text)
        return {"bytes": len(text),
                "top_level_keys": sorted(body),
                "config_keys": sorted((body.get("config") or {})),
                "storage_credentials": len(body.get("storage-credentials") or [])}

    with_shape = shape(ok_text(session.get(url)))
    without_shape = shape(without_header(lambda: ok_text(session.get(url)))())

    layers = [
        ("GET, header sent", lambda: ok_text(session.get(url))),
        ("GET, header removed", without_header(lambda: ok_text(session.get(url)))),
        ("+ TableResponse parse", lambda: TableResponse.model_validate_json(
            ok_text(session.get(url)))),
        ("whole load_table", lambda: catalog.load_table(ident)),
        ("whole load_table, no header", without_header(lambda: catalog.load_table(ident))),
    ]
    timings = timed_interleaved(layers, args.iters)

    out = []
    w = out.append
    w("# load_table on %s, with and without %s." % (cat["name"], HEADER))
    w("# Generated by bench_delegation.py. Same catalog object, same session,")
    w("# same URL in every row; rows are interleaved.")
    w("")
    w("  client      pyiceberg %s on python %s" % (pyiceberg.__version__,
                                                   sys.version.split()[0]))
    w("  header      %s: %s  (set by pyiceberg's session by default)" % (HEADER, sent))
    w("  iterations  %d, after 5 discarded, per row" % args.iters)
    w("  measured    %s" % time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))
    w("")
    w("## p50 per row (milliseconds)")
    w("")
    w("  %-30s %9s %9s %9s %8s" % ("row", "p50", "p90", "stdev", "2xSEM"))
    for name, _ in layers:
        s = timings[name]
        p50, p90, sd = us(s)
        w("  %-30s %9.1f %9.1f %9.1f %8.1f" % (name, p50 / 1000, p90 / 1000,
                                             sd / 1000, 2 * sem_us(s) / 1000))
    w("")
    w("  p50 differences, with a 95% bootstrap interval; separable only when")
    w("  the interval excludes zero")
    w("")
    for label, x, y in (
            ("header cost at transport", "GET, header sent", "GET, header removed"),
            ("header cost through the method", "whole load_table",
             "whole load_table, no header"),
            ("client above transport, header removed",
             "whole load_table, no header", "GET, header removed")):
        diff = (us(timings[x])[0] - us(timings[y])[0]) / 1000
        lo, hi = p50_diff_interval(timings[x], timings[y])
        lo, hi = lo / 1e6, hi / 1e6
        w("  %-40s %+8.1f ms  [%+.1f, %+.1f]  %s" % (
            label, diff, lo, hi,
            "separable" if lo > 0 or hi < 0 else "NO -- interval spans zero"))
    w("")
    w("## Response shape, key names only")
    w("")
    for label, sh in (("header sent", with_shape), ("header removed", without_shape)):
        w("  %s" % label)
        w("    bytes                %d" % sh["bytes"])
        w("    top-level keys       %s" % ", ".join(sh["top_level_keys"]))
        w("    config keys          %s" % (", ".join(sh["config_keys"]) or "(none)"))
        w("    storage-credentials  %d" % sh["storage_credentials"])
    w("")

    text = "\n".join(out) + "\n"
    pairs = redact.values_for(cat, redact.secret_env_names(cat))
    text = redact.scrub(text, pairs)
    redact.verify({"text": text}, pairs)
    name = "bench-delegation-%s-%s.txt" % (
        cat["name"], time.strftime("%Y%m%dT%H%M%SZ", time.gmtime()))
    path = os.path.join(HERE, "evidence", name)
    with open(path, "w") as fh:
        fh.write(text)
    # The samples, beside the text, so the interval can be re-derived.
    with open(path.replace(".txt", ".json"), "w") as fh:
        json.dump({"catalog": cat["name"], "unit": "ns",
                   "samples": {k: v for k, v in timings.items()}}, fh)
        fh.write("\n")
    print(text)
    print("wrote %s" % os.path.relpath(path, HERE))


if __name__ == "__main__":
    main()
