#!/usr/bin/env python3
"""Render the stored benchmark runs as readable evidence. No network, no timing.

    $ python3 bench_report.py
    wrote evidence/bench-comparison.txt   1 catalog

Everything printed here is computed in bench.py from stored samples and read
out of the file. Nothing is recomputed by eye, and the samples stay in the JSON
so any figure in the paper can be re-derived without re-running anything.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from make_surface import _wrap                       # noqa: E402

EV = os.path.join(HERE, "evidence")
OUT = os.path.join(EV, "bench-comparison.txt")


def runs():
    """Every stored run, grouped by catalog, oldest first."""
    by_catalog = {}
    for name in sorted(os.listdir(EV)):
        # bench-<catalog>-<ts>.json only. bench-delegation-*.json holds
        # another script's samples and has no meta block.
        if (name.startswith("bench-") and name.endswith(".json")
                and not name.startswith(("bench-delegation-", "bench-breakdown-"))):
            with open(os.path.join(EV, name)) as fh:
                doc = json.load(fh)
            by_catalog.setdefault(doc["meta"]["catalog"], []).append(doc)
    for catalog in by_catalog:
        by_catalog[catalog].sort(key=lambda d: d["meta"]["measured_utc"])
    return by_catalog


def stability(docs):
    """p50 per op across runs of one catalog, and the spread between them.

    Two runs an hour apart on an idle machine moved these by about a tenth.
    Quoting one run's p50 as the number would be quoting the machine's mood,
    so the spread is printed next to it and computed here rather than eyed.
    """
    rows = []
    ops = docs[0]["meta"]["ops"]
    for op in ops:
        row = {"op": op}
        for client in ("rust", "pyiceberg"):
            p50s = []
            for doc in docs:
                for st in doc["stats"]:
                    if st["op"] == op and client in st:
                        p50s.append(st[client]["p50_us"])
            if p50s:
                row[client] = {
                    "runs": len(p50s), "min": min(p50s), "max": max(p50s),
                    "spread_pct": round((max(p50s) - min(p50s))
                                        / min(p50s) * 100.0, 1),
                }
        ratios = [st["p50_ratio_py_over_rust"] for doc in docs
                  for st in doc["stats"]
                  if st["op"] == op and "p50_ratio_py_over_rust" in st]
        if ratios:
            row["ratio"] = {"min": min(ratios), "max": max(ratios)}
        rows.append(row)
    return rows


def main():
    out = []
    by_catalog = runs()
    docs = [d for group in by_catalog.values() for d in group]
    w = out.append

    w("# The same operations through both clients, timed.")
    w("# Generated by bench_report.py from the stored samples in")
    w("# evidence/bench-*.json. Percentiles are computed by bench.py at")
    w("# collection time; this file only formats them.")
    w("")

    for catalog, group in by_catalog.items():
      for doc in group:
        m = doc["meta"]
        w("## %s   (run %d of %d)" % (
            m["catalog"], group.index(doc) + 1, len(group)))
        w("")
        w("  rust        %s, %s build, %s" % (
            m["rust_client"], m["rust_profile"], m["rustc"]))
        w("  pyiceberg   %s on python %s" % (m["pyiceberg"], m["python"]))
        w("  run         %d rounds x %d iterations, %d warmup discarded per op "
          "per round" % (m["rounds"], m["iters_per_round"], m["warmup_per_round"]))
        w("  storage     %s   cpus %s   %s" % (
            m["storage_factory"], m["cpu_count"], m["measured_utc"]))
        w("  samples     %d, all stored" % m["sample_count"])
        if m.get("errors"):
            w("  errors      %d round(s) exited non-zero -- see the JSON"
              % len(m["errors"]))
        w("")

        w("  steady state, one catalog object already built, microseconds")
        w("")
        w("  %-18s %9s %9s %9s %9s %9s %9s  %s" % (
            "op", "rust p50", "rust p99", "rust sd", "py p50", "py p99",
            "py sd", "py/rust"))
        for row in doc["stats"]:
            r, p = row.get("rust"), row.get("pyiceberg")
            if not r or not p:
                w("  %-18s %s" % (row["op"], "one client only"))
                continue
            w("  %-18s %9.1f %9.1f %9.1f %9.1f %9.1f %9.1f  %6.2fx" % (
                row["op"], r["p50_us"], r["p99_us"], r["stdev_us"],
                p["p50_us"], p["p99_us"], p["stdev_us"],
                row.get("p50_ratio_py_over_rust", 0)))
        w("")

        cold = doc.get("cold_start_wall") or {}
        if cold:
            w("  cold start: spawn to exit, catalog built and each op answered once, ms")
            w("")
            w("  %-18s %9s %9s %9s %6s" % ("client", "p50", "min", "max", "n"))
            for client in ("rust", "pyiceberg"):
                c = cold.get(client)
                if c:
                    w("  %-18s %9.1f %9.1f %9.1f %6d" % (
                        client, c["p50_us"] / 1000.0, c["min_us"] / 1000.0,
                        c["max_us"] / 1000.0, c["n"]))
            if "rust" in cold and "pyiceberg" in cold and cold["rust"]["p50_us"]:
                w("")
                w("  %.1fx, and it is paid once per process rather than once "
                  "per call." % (cold["pyiceberg"]["p50_us"]
                                 / cold["rust"]["p50_us"]))
            w("")

    for catalog, group in by_catalog.items():
        if len(group) < 2:
            continue
        w("## %s, across %d runs" % (catalog, len(group)))
        w("")
        w("  p50 in microseconds, lowest and highest of the stored runs")
        w("")
        w("  %-18s %9s %9s %7s   %9s %9s %7s   %s" % (
            "op", "rust min", "rust max", "spread", "py min", "py max",
            "spread", "py/rust range"))
        for row in stability(group):
            r_, p_ = row.get("rust"), row.get("pyiceberg")
            if not r_ or not p_:
                continue
            ratio = row.get("ratio") or {}
            # Printed as a range, and printed here rather than worked out in
            # prose: a figure quoted in an article has to exist in an artifact,
            # and "1.9x to 3.2x" rounded by hand exists in none.
            span = ("%.2fx to %.2fx" % (ratio["min"], ratio["max"])
                    if ratio and ratio["min"] != ratio["max"]
                    else ("%.2fx" % ratio["min"] if ratio else "--"))
            w("  %-18s %9.1f %9.1f %6.1f%%   %9.1f %9.1f %6.1f%%   %s" % (
                row["op"], r_["min"], r_["max"], r_["spread_pct"],
                p_["min"], p_["max"], p_["spread_pct"], span))
        # Cold start across runs, and the per-run difference, computed here so
        # no article subtracts two ranges by hand.
        pairs = [(d["cold_start_wall"]["rust"]["p50_us"] / 1000.0,
                  d["cold_start_wall"]["pyiceberg"]["p50_us"] / 1000.0,
                  d["meta"]["measured_utc"][:10])
                 for d in group
                 if "rust" in d.get("cold_start_wall", {})
                 and "pyiceberg" in d.get("cold_start_wall", {})]
        if pairs:
            diffs = [py - r for r, py, _ in pairs]
            ratios = [py / r for r, py, _ in pairs]
            w("")
            w("  cold start p50 across runs, milliseconds")
            w("    rust         %.1f to %.1f" % (min(p[0] for p in pairs), max(p[0] for p in pairs)))
            w("    pyiceberg    %.1f to %.1f" % (min(p[1] for p in pairs), max(p[1] for p in pairs)))
            w("    difference   %.1f to %.1f, per run, pyiceberg minus rust"
              % (min(diffs), max(diffs)))
            w("    ratio        %.1fx to %.1fx" % (min(ratios), max(ratios)))
            w("    dates        %s" % ", ".join(sorted(set(p[2] for p in pairs))))
        w("")

    w("## Reading these numbers honestly")
    w("")
    items = [
        "The control catalog is a local container over loopback. That is "
        "deliberate -- it is the only configuration where the client's own "
        "cost is visible instead of the network's -- and it is also why these "
        "ratios are an upper bound. Over a real network the round trip is on "
        "both sides of every ratio and moves it towards 1; the vendor sections "
        "above are that, measured.",
        "Where two clients do not send the same request, a ratio is not a "
        "client comparison. pyiceberg sends X-Iceberg-Access-Delegation: "
        "vended-credentials by default and iceberg-catalog-rest sends nothing, "
        "so a catalog that vends credentials on load_table is timed doing that "
        "work for one client only. bench_delegation.py measures that row with "
        "the header on and off; read load_table beside it.",
        "The two operations where the clients are nearly equal, load_table and "
        "head_table, are the two where the server does the most work. That is "
        "the same effect seen from the other end, and it is the check that "
        "this harness is measuring the clients rather than itself.",
        "Cold start is the figure that survives the network, because it is a "
        "fixed cost paid before any request. It matters for a CLI, a lambda "
        "or a short-lived agent process, and not at all for a long-running "
        "service.",
        "A release build is required; bench.py refuses to write evidence from "
        "a debug binary. Both clients are spawned as fresh processes, both "
        "build their catalog and warm up before recording, and the clients "
        "alternate which goes first each round.",
        "Runs of the same benchmark on an idle machine move p50 by as much as "
        "the spread columns above show -- a figure computed from the stored "
        "runs, not asserted here. One run is a number; the spread across runs is the "
        "measurement, which is why every run is kept as its own file and the "
        "report prints the range.",
        "Nothing here says anything about correctness, and speed is not a "
        "reason to choose a client that cannot reach the operations a "
        "workload needs. The surface tables are the other half of this.",
    ]
    for item in items:
        for line in _wrap(item):
            w("  %s" % line)
        w("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(line.rstrip() for line in out).rstrip() + "\n")
    print("wrote %s   %d run(s) across %d catalog(s)" % (
        os.path.relpath(OUT, HERE), len(docs), len(by_catalog)))


if __name__ == "__main__":
    main()
