#!/usr/bin/env python3
"""Put the two clients in one table, and check them against what paper 1
measured on the same catalog.

    $ python3 compare_clients.py               # no network
    wrote evidence/client-comparison.txt   25 endpoints, 1 catalog run by both

Nothing here measures anything. It joins four things that were measured
separately: the two operation maps, read from each client's source; the two
runs, one per client against the same catalog with the same fixture; and paper
1's own evidence for that catalog, which is what makes a gated cell legible --
a client refusing to call an endpoint means one thing if the catalog serves it
and another if it does not.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CONF = os.path.join(HERE, os.pardir, "iceberg-conformance")
sys.path.insert(0, CONF)

import yaml                                          # noqa: E402
from probe.spec import PROBES, WRITE_PROBES          # noqa: E402
import operation_map as rust                         # noqa: E402
import pyiceberg_map as py                           # noqa: E402
import run_rust                                      # noqa: E402
import run_pyiceberg                                 # noqa: E402
from make_surface import _wrap, entry                # noqa: E402

OUT = os.path.join(HERE, "evidence", "client-comparison.txt")
PAPER1 = os.path.join(HERE, os.pardir, "papers",
                      "iceberg-rest-catalog-conformance", "evidence")

RUNNABLE = {"reachable", "implicit"}


def load_runs(kind):
    """Every run of one client, by catalog name."""
    runs = {}
    for name in sorted(os.listdir(os.path.join(HERE, "evidence"))):
        prefix, suffix = "%s-run-" % kind, ".json"
        if name.startswith(prefix) and name.endswith(suffix) and ".failed." not in name:
            with open(os.path.join(HERE, "evidence", name)) as fh:
                runs[name[len(prefix):-len(suffix)]] = json.load(fh)
    return runs


def paper1(catalog):
    """Paper 1's verdicts for one catalog, by probe. Absent is not an error."""
    path = os.path.join(PAPER1, "%s.json" % catalog)
    if not os.path.exists(path):
        return None
    with open(path) as fh:
        doc = json.load(fh)
    return {p["probe"]: p for p in doc["probes"]}


def main():
    probes = list(PROBES) + list(WRITE_PROBES)
    by_id = {p.id: p for p in probes}
    rust_runs, py_runs = load_runs("rust"), load_runs("pyiceberg")
    both = sorted(set(rust_runs) & set(py_runs))

    out = []
    w = out.append
    w("# The same probe list through two clients, against the same catalogs.")
    w("# Generated by compare_clients.py from the two operation maps and the")
    w("# stored runs. Join only -- no network, and nothing measured here.")
    w("")
    w("  rust        %s, map read %s" % (rust.CRATE, rust.READ_ON))
    w("  pyiceberg   %s, map read %s" % (py.CLIENT, py.READ_ON))
    w("")
    w("  Both are subjects. `control` in this directory means the control")
    w("  catalog, Apache Polaris, and never one of the clients.")
    w("")

    # ------------------------------------------------- surface, side by side
    w("## What each client can express, by endpoint signature")
    w("")
    w("  Variants are folded into the endpoint they vary: paper 1's rule, for")
    w("  paper 1's reason. A `+` is expressible, a `-` is not.")
    w("")
    w("  %-66s %-5s %s" % ("endpoint", "rust", "py"))
    counts = {"rust": 0, "py": 0, "total": 0}
    rows = []
    for p in probes:
        if p.variant_of:
            continue
        r_status = entry(rust, p.id)[0]
        p_status = entry(py, p.id)[0]
        counts["total"] += 1
        counts["rust"] += r_status in RUNNABLE
        counts["py"] += p_status in RUNNABLE
        rows.append((p.signature(), r_status, p_status))
    for sig, r_status, p_status in rows:
        w("  %-66s %-5s %s" % (
            sig,
            "+" if r_status in RUNNABLE else "-",
            "+" if p_status in RUNNABLE else "-"))
    w("")
    w("  rust  %2d of %d        pyiceberg  %2d of %d" % (
        counts["rust"], counts["total"], counts["py"], counts["total"]))
    w("")

    w("  The %d endpoints pyiceberg reaches and the crate does not:"
      % sum(1 for _, r, p in rows if p in RUNNABLE and r not in RUNNABLE))
    for sig, r_status, p_status in rows:
        if p_status in RUNNABLE and r_status not in RUNNABLE:
            w("    %-66s rust: %s" % (sig, r_status))
    w("")
    ahead = [(sig, r, p) for sig, r, p in rows if r in RUNNABLE and p not in RUNNABLE]
    w("  The other direction, %d: endpoints the crate reaches and pyiceberg" % len(ahead))
    w("  does not.")
    for sig, r_status, p_status in ahead:
        w("    %-66s py: %s" % (sig, p_status))
    if not ahead:
        w("    (none)")
    w("")

    # ------------------------------------------------------------ the runs
    for catalog in both:
        r_doc, p_doc = rust_runs[catalog], py_runs[catalog]
        r_rows = {row["probe"]: row for row in r_doc["rows"]}
        p_rows = {row["probe"]: row for row in p_doc["rows"]}
        p1 = paper1(catalog)

        w("## %s, measured through both" % catalog)
        w("")
        w("  rust        %s, %s, storage %s" % (
            r_doc["meta"]["crate"], r_doc["meta"]["measured_utc"],
            r_doc["meta"].get("storage_factory")))
        w("  pyiceberg   %s, %s, %d endpoints declared" % (
            p_doc["meta"]["client"], p_doc["meta"]["measured_utc"],
            len(p_doc["meta"].get("endpoints_declared", []))))
        w("")
        w("  %-30s %-16s %-16s %s" % ("probe", "rust", "pyiceberg", "paper 1"))
        for p in probes:
            r_v = r_rows.get(p.id, {}).get("verdict", "--")
            p_v = p_rows.get(p.id, {}).get("verdict", "--")
            p1_v = (p1 or {}).get(p.id, {}).get("verdict", "--")
            w("  %-30s %-16s %-16s %s" % (p.id, r_v, p_v, p1_v))
        w("")
        for label, doc in (("rust", r_doc), ("pyiceberg", p_doc)):
            w("  %-11s %s" % (label, ", ".join(
                "%d %s" % (v, k.lower())
                for k, v in sorted(doc["meta"]["counts"].items()))))
        w("")

        # --------------------------------------------- the gate, cross-checked
        gated = [pid for pid, row in p_rows.items()
                 if row["verdict"] in ("GATED", "SUBSTITUTED")]
        if gated and p1:
            w("  ### Where pyiceberg refused, and what paper 1 saw")
            w("")
            for line in _wrap(
                    "pyiceberg compares each endpoint against the `endpoints` "
                    "array of GET /v1/config before sending anything. Paper 1 "
                    "sent the request regardless, so the two together say "
                    "whether the refusal cost anything."):
                w("  %s" % line)
            w("")
            for pid in sorted(gated):
                row = p_rows[pid]
                served = (p1.get(pid) or {}).get("verdict", "--")
                declared = (p1.get(pid) or {}).get("declared")
                w("  %s  [%s, gate %s]" % (pid, row["verdict"], row.get("gate")))
                w("      declared by the catalog   %s" % (
                    "yes" if row.get("endpoint_declared") else "no"))
                w("      paper 1, same endpoint    %s (declared: %s)" % (
                    served, declared))
                w("      %s" % (
                    "The endpoint answers; this client will not ask."
                    if served == "OK" and not row.get("endpoint_declared")
                    else "Client and catalog agree; the gate cost nothing."))
                w("")

    # ------------------------------------------------------------ auth, seven
    cfg_path = os.path.join(CONF, "catalogs.yaml")
    if os.path.exists(cfg_path):
        w("## Auth, across every catalog the two papers share")
        w("")
        for line in _wrap(
                "Catalog names and auth kinds only. This is the axis on which "
                "the two clients differ before a single probe is issued: the "
                "REST crate ships no request signer, so two of the seven "
                "cannot be reached through it, while pyiceberg mounts botocore "
                "and can. Rust reaches those two only by leaving the REST "
                "protocol for iceberg-catalog-glue or iceberg-catalog-s3tables, "
                "which is a loss of protocol uniformity rather than of "
                "capability."):
            w("  %s" % line)
        w("")
        cfg = yaml.safe_load(open(cfg_path))
        w("  %-20s %-16s %-10s %-10s %s" % (
            "catalog", "auth", "rust", "py", "configured"))
        tally = {"rust": 0, "py": 0}
        for cat in cfg["catalogs"]:
            kind = (cat.get("auth") or {}).get("type", "none")
            r_mode = run_rust.auth_plan(cat.get("auth"))[0]
            p_mode = run_pyiceberg.auth_plan(cat.get("auth"))[0]
            tally["rust"] += r_mode != "absent"
            tally["py"] += p_mode != "absent"
            w("  %-20s %-16s %-10s %-10s %s" % (
                cat["name"], kind, r_mode, p_mode,
                "yes" if cat.get("enabled", True) else "placeholder"))
        w("")
        w("  reachable auth   rust %d of %d, pyiceberg %d of %d" % (
            tally["rust"], len(cfg["catalogs"]), tally["py"], len(cfg["catalogs"])))
        w("")
        placeholders = [c["name"] for c in cfg["catalogs"]
                        if not c.get("enabled", True)]
        if placeholders:
            for line in _wrap(
                    "A row marked placeholder is carrying example config, so "
                    "its auth kind is the example's and not the account's. "
                    "Paper 1 measured %s on credentials this configuration no "
                    "longer holds -- Horizon in particular with a "
                    "keypair-signed JWT sent as a bare client_secret, which is "
                    "a different row in both clients' auth tables than the "
                    "oauth2 above." % " and ".join(placeholders)):
                w("  %s" % line)
            w("")

    w("## What this comparison does not say")
    w("")
    for item in (
        "Expressible is not correct. A `+` means the client can issue the "
        "request, not that what comes back is right.",
        "A run is one catalog at one moment, and only the control catalog has "
        "been run by both clients so far. The vendor columns are unmeasured, "
        "not empty.",
        "Both clients were pointed at the same fixture table through the same "
        "credentials. Where they disagree the difference is the client; where "
        "they agree it is not evidence that every catalog behaves this way.",
    ):
        for line in _wrap(item):
            w("  %s" % line)
        w("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(line.rstrip() for line in out).rstrip() + "\n")
    print("wrote %s   %d endpoints, %d catalog(s) run by both" % (
        os.path.relpath(OUT, HERE), counts["total"], len(both)))


if __name__ == "__main__":
    main()
