#!/usr/bin/env python3
"""What one client's declaration gate would cost on each of the seven catalogs.

    $ python3 gate_cost.py                     # no network
    wrote evidence/declaration-gate-cost.txt   7 catalogs

pyiceberg refuses to call an endpoint the catalog did not name in the
`endpoints` array of GET /v1/config; the Rust crate has no such check and sends
whatever it can build. Paper 1 already measured, for all seven catalogs, which
endpoints are declared and which actually work. Joining the two says how many
working endpoints each client can reach in practice, which is a different
number from how many it can express.

Measured on the control catalog, modelled everywhere else. Polaris is the only
catalog where both clients have been run; for the other six this reads the stored
/v1/config response from paper 1 and applies the client's own rules to it. Each
row says which it is, and a vendor run can falsify the modelled ones.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, os.pardir, "iceberg-conformance"))

from probe.spec import PROBES, WRITE_PROBES          # noqa: E402
import operation_map as rust                         # noqa: E402
import pyiceberg_map as py                           # noqa: E402
from make_surface import _wrap, entry, RUNNABLE      # noqa: E402

PAPER1 = os.path.join(HERE, os.pardir, "papers",
                      "iceberg-rest-catalog-conformance", "evidence")
OUT = os.path.join(HERE, "evidence", "declaration-gate-cost.txt")

# pyiceberg's fallback for a catalog that returns no `endpoints` array at all
# (rest/__init__.py:198, :734). Twelve namespace and table endpoints; the HEADs,
# credentials, scan planning and the views are not among them. View endpoints
# are added only if the caller sets view-endpoints-supported, which defaults to
# False (:269-270), so a default caller does not get them.
DEFAULT_ENDPOINTS = [
    "GET /v1/{prefix}/namespaces",
    "GET /v1/{prefix}/namespaces/{namespace}",
    "POST /v1/{prefix}/namespaces",
    "POST /v1/{prefix}/namespaces/{namespace}/properties",
    "DELETE /v1/{prefix}/namespaces/{namespace}",
    "GET /v1/{prefix}/namespaces/{namespace}/tables",
    "GET /v1/{prefix}/namespaces/{namespace}/tables/{table}",
    "POST /v1/{prefix}/namespaces/{namespace}/tables",
    "POST /v1/{prefix}/namespaces/{namespace}/tables/{table}",
    "DELETE /v1/{prefix}/namespaces/{namespace}/tables/{table}",
    "POST /v1/{prefix}/tables/rename",
    "POST /v1/{prefix}/namespaces/{namespace}/register",
]

WORKS = ("declared, works", "undeclared, works")


def load(catalog):
    path = os.path.join(PAPER1, "%s.json" % catalog)
    with open(path) as fh:
        return json.load(fh)


def catalogs():
    return sorted(f[:-len(".json")] for f in os.listdir(PAPER1)
                  if f.endswith(".json") and f != "conformance-matrix.json")


def gate_for(probe_id):
    return entry(py, probe_id)[4]


def main():
    probes = [p for p in list(PROBES) + list(WRITE_PROBES) if not p.variant_of]
    out, w = [], None
    out = []
    w = out.append

    w("# What pyiceberg's declaration gate costs, catalog by catalog.")
    w("# Generated by gate_cost.py. A join over paper 1's stored evidence and")
    w("# the two client maps -- no network, and nothing measured here that was")
    w("# not measured somewhere else first.")
    w("")
    for line in _wrap(
            "pyiceberg compares every endpoint against the `endpoints` array "
            "of GET /v1/config before sending (rest/__init__.py:649). The Rust "
            "crate has no such check. So for an endpoint a catalog serves "
            "without declaring, the two clients differ on whether the request "
            "is sent at all -- and the client that can express fewer "
            "operations is the one that will try."):
        w("  %s" % line)
    w("")
    for line in _wrap(
            "Paper 1's words are used unchanged: `undeclared, works` is an "
            "endpoint that answered without being named, `DECLARED, FAILS` is "
            "the other direction."):
        w("  %s" % line)
    w("")

    summary = []
    detail = []
    for name in catalogs():
        doc = load(name)
        declared = list(doc["declared_endpoints"])
        fallback = not declared
        effective = set(DEFAULT_ENDPOINTS if fallback else declared)

        by_probe = {p["probe"]: p for p in doc["probes"]}
        blocked, substituted, sent, rust_can = [], [], 0, []
        overclaimed = []
        for p in probes:
            row = by_probe.get(p.id) or {}
            reconciled = row.get("reconciled")
            if reconciled == "DECLARED, FAILS":
                overclaimed.append(p.id)
            if reconciled not in WORKS:
                continue
            if p.signature() in effective:
                sent += 1
                continue
            gate = gate_for(p.id)
            if gate in ("refuses", "silent-empty"):
                blocked.append((p.id, p.signature(), gate))
                if entry(rust, p.id)[0] in RUNNABLE:
                    rust_can.append(p.id)
            elif gate == "substitutes":
                substituted.append((p.id, p.signature()))
            else:
                sent += 1                            # ungated; sent regardless

        summary.append((name, len(declared), fallback, sent, len(blocked),
                        len(substituted), len(rust_can), len(overclaimed)))
        detail.append((name, declared, fallback, blocked, substituted,
                       rust_can, overclaimed, doc.get("run_at", "")))

    w("## Working endpoints, and whether the gate lets the client ask")
    w("")
    w("  %-22s %-9s %-7s %-8s %-12s %s" % (
        "catalog", "declared", "sends", "blocked", "substituted", "of blocked,"))
    w("  %-22s %-9s %-7s %-8s %-12s %s" % (
        "", "", "", "", "", "rust can send"))
    for name, n_declared, fallback, sent, n_blocked, n_sub, n_rust, _over in summary:
        w("  %-22s %-9s %-7d %-8d %-12d %d" % (
            name, "none" if fallback else n_declared, sent, n_blocked, n_sub,
            n_rust))
    w("")
    w("  declared    size of the catalog's `endpoints` array. `none` means the")
    w("              array was absent, and the client falls back to twelve")
    w("              namespace and table endpoints -- no HEADs, no credentials,")
    w("              no scan planning, and no views unless the caller asks.")
    w("  sends       working endpoints the gate lets through.")
    w("  blocked     working endpoints the client refuses to call, or answers")
    w("              with an empty list without calling.")
    w("  substituted working endpoints answered by a different request.")
    w("")

    # The size of the effect, computed rather than characterised. A mechanism
    # that is real and nearly free is a finding, and it is the kind that gets
    # written up as bigger than it is if the counting is left to the prose.
    blocked_total = sum(r[4] for r in summary)
    sub_total = sum(r[5] for r in summary)
    clean = [r[0] for r in summary if r[4] == 0 and r[5] == 0]
    blocked_ids = sorted({pid for _n, _d, _f, b, _s, _r, _o, _t in detail
                          for pid, _sig, _g in b})
    rust_total = sum(r[6] for r in summary)
    w("## The size of it")
    w("")
    for line in _wrap(
            "Across the seven catalogs the gate blocks %d working endpoint(s) "
            "in total, %s, and substitutes a different request for %d more. %d "
            "of the seven are untouched by it. In %d of the blocked cases the "
            "Rust crate could have sent the request, so on this evidence the "
            "gate does not move the comparison between the two clients."
            % (blocked_total,
               "all of them %s" % ", ".join(blocked_ids) if blocked_ids
               else "none", sub_total, len(clean), rust_total)):
        w("  %s" % line)
    w("")
    for line in _wrap(
            "The mechanism is real and the cost is small, which is two "
            "separate statements and both belong in the paper. What makes the "
            "cost small here is that the endpoints catalogs underclaim are "
            "mostly ones neither client can use: the one endpoint blocked on "
            "two catalogs is loadCredentials, which the Rust crate has no "
            "method for at all."):
        w("  %s" % line)
    w("")

    w("## Endpoint by endpoint")
    w("")
    for (name, declared, fallback, blocked, substituted, rust_can, over,
         run_at) in detail:
        w("  ### %s   (%s, paper 1 run %s)" % (
            name,
            "no endpoints array; client falls back to the twelve defaults"
            if fallback else "%d endpoints declared" % len(declared),
            run_at))
        w("")
        if not blocked and not substituted:
            w("      nothing blocked: every working endpoint is declared.")
            w("")
        for probe_id, sig, gate in blocked:
            r_status = entry(rust, probe_id)[0]
            w("      %-26s %s" % (probe_id, sig))
            w("      %-26s works on the wire, client %s" % ("", gate))
            w("      %-26s rust: %s" % (
                "", "would send it" if r_status in RUNNABLE
                else "cannot express it either (%s)" % r_status))
            w("")
        for probe_id, sig in substituted:
            w("      %-26s %s" % (probe_id, sig))
            w("      %-26s works on the wire, answered by another request" % "")
            w("")
        if over:
            for line in _wrap(
                    "The gate is not a correctness filter, only a filter on "
                    "underclaims. %s: %s -- declared and does not work, so "
                    "the client sends the request and gets the catalog's "
                    "error, exactly as the Rust crate would."
                    % (name, ", ".join(sorted(over)))):
                w("      %s" % line)
            w("")

    w("## What is measured here and what is modelled")
    w("")
    for item in (
        "apache-polaris is measured: both clients have been run against it, "
        "and evidence/pyiceberg-run-apache-polaris.json records the two cells "
        "the client refused.",
        "The other six are modelled. The `endpoints` array is paper 1's, read "
        "from a stored /v1/config response; what the client does with it is "
        "read from the client's source. Neither client has been run against "
        "those catalogs, so every row for them is a prediction that a vendor "
        "run can falsify -- which is the point of writing it down first.",
        "Paper 1's own caveats carry over unchanged: three of the seven were "
        "measured on trial accounts, managed catalogs expose no version, and "
        "each run is one region at one moment.",
    ):
        for line in _wrap(item):
            w("  %s" % line)
        w("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(line.rstrip() for line in out).rstrip() + "\n")
    print("wrote %s   %d catalogs" % (os.path.relpath(OUT, HERE), len(summary)))


if __name__ == "__main__":
    main()
