#!/usr/bin/env python3
"""Join operation_map.py against paper 1's probe list and write the evidence.

Run before every commit that touches either side. The join fails loudly rather
than skipping, for the reason the anonymiser fails loudly: a mapping that has
quietly gone stale reads exactly like a mapping that is correct.

    $ python3 make_surface.py
    wrote evidence/rust-client-operation-surface.txt   33 probes
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, os.pardir, "iceberg-conformance"))

from probe.spec import PROBES, WRITE_PROBES          # noqa: E402
import operation_map as om                           # noqa: E402

OUT = os.path.join(HERE, "evidence", "rust-client-operation-surface.txt")

STATUSES = ("reachable", "implicit", "degraded", "unsupported", "absent")
# What a status means for the run that follows. A probe that cannot be issued
# is not a failed probe, and must never be scored as one.
RUNNABLE = {"reachable", "implicit"}


def check(probes):
    """Refuse to write anything if the two sides have drifted apart."""
    ids = [p.id for p in probes]
    missing = [i for i in ids if i not in om.MAP]
    stale = [i for i in om.MAP if i not in ids]
    bad = [(i, v[0]) for i, v in om.MAP.items() if v[0] not in STATUSES]
    if missing:
        sys.exit("probes with no mapping: %s" % ", ".join(missing))
    if stale:
        sys.exit("mapped probes that no longer exist in spec.py: %s"
                 % ", ".join(stale))
    if bad:
        sys.exit("unknown status: %s" % bad)


def main():
    probes = list(PROBES) + list(WRITE_PROBES)
    check(probes)

    out = []
    w = out.append
    w("# Paper 1's probe list, mapped onto %s." % om.CRATE)
    w("# Generated by make_surface.py from operation_map.py, which was read")
    w("# from the published crate source on %s. Not a measurement: this is" % om.READ_ON)
    w("# what the client can attempt, before any catalog is involved.")
    w("")

    counts = dict.fromkeys(STATUSES, 0)
    for label, subset in (("read surface", PROBES), ("write surface", WRITE_PROBES)):
        w("## %s (%d probes)" % (label, len(subset)))
        w("")
        w("  %-30s %-12s %-11s %s" % ("probe", "surface", "status", "rust symbol"))
        for p in subset:
            status, symbol, ref, _ = om.MAP[p.id]
            counts[status] += 1
            w("  %-30s %-12s %-11s %s" % (
                p.id, p.surface, status,
                "%s  (%s)" % (symbol, ref) if symbol else "--"))
        w("")

    w("## Totals across all %d probes" % len(probes))
    w("")
    for s in STATUSES:
        w("  %-12s %2d" % (s, counts[s]))
    w("")
    runnable = sum(counts[s] for s in RUNNABLE)
    w("  %d of %d probes can be issued through this client at all." % (
        runnable, len(probes)))
    w("  The other %d are not failures to be scored -- there is no request to" % (
        len(probes) - runnable))
    w("  send. A run reports them as NOT-EXPRESSIBLE, never as a red cell.")
    w("")

    # Paper 1's own rule: several probes share one endpoint, so a per-probe
    # count is not a count of operations. update_table alone carries five
    # probes. Variants -- probes that differ from another only by a query
    # parameter -- are excluded here for the same reason the declaration tier
    # excludes them: they do not name a distinct endpoint.
    w("## The same thing counted by endpoint signature, not by probe")
    w("")
    seen = {}
    for p in probes:
        if p.variant_of:
            continue
        status = om.MAP[p.id][0]
        sig = p.signature()
        if sig in seen and seen[sig][0] != status:
            sys.exit("signature %s has mixed statuses: %s and %s"
                     % (sig, seen[sig][0], status))
        seen.setdefault(sig, (status, []))[1].append(p.id)
    w("  %-11s %-52s %s" % ("status", "endpoint", "probes"))
    for sig, (status, ids) in sorted(seen.items(), key=lambda kv: kv[1][0]):
        w("  %-11s %-52s %s" % (status, sig, ", ".join(ids)))
    w("")
    sig_runnable = sum(1 for st, _ in seen.values() if st in RUNNABLE)
    w("  %d of %d distinct endpoints are expressible through this client." % (
        sig_runnable, len(seen)))
    w("  Counted per probe the figure is %d of %d, which is the same fact" % (
        runnable, len(probes)))
    w("  weighted by how many probes paper 1 happened to point at one endpoint.")
    w("")

    w("## Notes, per probe that is not a plain `reachable`")
    w("")
    for p in probes:
        status, symbol, ref, note = om.MAP[p.id]
        if status == "reachable" and not note:
            continue
        w("  %s  [%s]" % (p.id, status))
        for line in _wrap(note or "(no note)"):
            w("      %s" % line)
        w("")

    w("## Reached by the crate, not probed by paper 1")
    w("")
    for name, symbol, ref, note in om.BEYOND_THE_SWEEP:
        w("  %s  --  %s  (%s)" % (name, symbol, ref))
        for line in _wrap(note):
            w("      %s" % line)
        w("")

    w("## Not verified, and therefore not claimed")
    w("")
    for item in om.UNVERIFIED:
        for line in _wrap(item):
            w("  %s" % line)
        w("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(out).rstrip() + "\n")
    print("wrote %s   %d probes" % (
        os.path.relpath(OUT, HERE), len(probes)))


def _wrap(text, width=68):
    words, line, lines = text.split(), "", []
    for word in words:
        if line and len(line) + 1 + len(word) > width:
            lines.append(line)
            line = word
        else:
            line = "%s %s" % (line, word) if line else word
    if line:
        lines.append(line)
    return lines


if __name__ == "__main__":
    main()
