#!/usr/bin/env python3
"""Join a client's operation map against paper 1's probe list, write the evidence.

One generator for both clients, so the two are described in the same words and
can be put in one table:

    $ python3 make_surface.py                  # the Rust crate
    wrote evidence/rust-client-operation-surface.txt   33 probes
    $ python3 make_surface.py --client pyiceberg
    wrote evidence/pyiceberg-client-operation-surface.txt   33 probes

Run before every commit that touches either side. The join fails loudly rather
than skipping, for the reason the anonymiser fails loudly: a mapping that has
quietly gone stale reads exactly like a mapping that is correct.
"""

import argparse
import importlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, os.pardir, "iceberg-conformance"))

from probe.spec import PROBES, WRITE_PROBES          # noqa: E402

# client name -> (module, the column heading for a symbol, output file,
#                 where the map was read from)
CLIENTS = {
    "rust": ("operation_map", "rust symbol",
             "rust-client-operation-surface.txt",
             "the published crate source"),
    "pyiceberg": ("pyiceberg_map", "symbol",
                  "pyiceberg-client-operation-surface.txt",
                  "the installed package"),
}

# The gate a client applies before sending a request at all. Only pyiceberg has
# one; a map without gates simply produces no section.
GATES = {
    "refuses": "raises before sending anything",
    "substitutes": "sends a different request that answers the same question",
    "silent-empty": "returns an empty result without sending anything",
}

STATUSES = ("reachable", "implicit", "degraded", "unsupported", "absent")
# What a status means for the run that follows. A probe that cannot be issued
# is not a failed probe, and must never be scored as one.
RUNNABLE = {"reachable", "implicit"}


def entry(om, probe_id):
    """(status, symbol, ref, note, gate). Gate is optional in a map."""
    row = om.MAP[probe_id]
    return tuple(row[:4]) + (row[4] if len(row) > 4 else None,)


def check(probes, om):
    """Refuse to write anything if the two sides have drifted apart."""
    ids = [p.id for p in probes]
    missing = [i for i in ids if i not in om.MAP]
    stale = [i for i in om.MAP if i not in ids]
    bad = [(i, v[0]) for i, v in om.MAP.items() if v[0] not in STATUSES]
    ungated = [i for i in ids if entry(om, i)[4] not in (None,) + tuple(GATES)]
    if missing:
        sys.exit("probes with no mapping: %s" % ", ".join(missing))
    if stale:
        sys.exit("mapped probes that no longer exist in spec.py: %s"
                 % ", ".join(stale))
    if bad:
        sys.exit("unknown status: %s" % bad)
    if ungated:
        sys.exit("unknown gate on: %s" % ", ".join(ungated))


def surface(client_name):
    modname, symbol_label, filename, provenance = CLIENTS[client_name]
    om = importlib.import_module(modname)
    label = getattr(om, "CRATE", None) or om.CLIENT
    out_path = os.path.join(HERE, "evidence", filename)

    probes = list(PROBES) + list(WRITE_PROBES)
    check(probes, om)

    out = []
    w = out.append
    w("# Paper 1's probe list, mapped onto %s." % label)
    w("# Generated by make_surface.py from %s.py, which was read" % modname)
    w("# from %s on %s. Not a measurement: this is" % (provenance, om.READ_ON))
    w("# what the client can attempt, before any catalog is involved.")
    w("")

    counts = dict.fromkeys(STATUSES, 0)
    for section, subset in (("read surface", PROBES), ("write surface", WRITE_PROBES)):
        w("## %s (%d probes)" % (section, len(subset)))
        w("")
        w("  %-30s %-12s %-11s %s" % ("probe", "surface", "status", symbol_label))
        for p in subset:
            status, symbol, ref, _, _gate = entry(om, p.id)
            counts[status] += 1
            w("  %-30s %-12s %-11s %s" % (
                p.id, p.surface, status,
                "%s  (%s)" % (symbol, ref) if symbol else "--"))
        w("")

    w("## Totals across all %d probes" % len(probes))
    w("")
    for s in STATUSES:
        w("  %-12s %2d" % (s, counts[s]))
    w("")
    runnable = sum(counts[s] for s in RUNNABLE)
    w("  %d of %d probes can be issued through this client at all." % (
        runnable, len(probes)))
    w("  The other %d are not failures to be scored -- there is no request to" % (
        len(probes) - runnable))
    w("  send. A run reports them as NOT-EXPRESSIBLE, never as a red cell.")
    w("")

    # Paper 1's own rule: several probes share one endpoint, so a per-probe
    # count is not a count of operations. update_table alone carries five
    # probes. Variants -- probes that differ from another only by a query
    # parameter -- are excluded here for the same reason the declaration tier
    # excludes them: they do not name a distinct endpoint.
    w("## The same thing counted by endpoint signature, not by probe")
    w("")
    seen = {}
    for p in probes:
        if p.variant_of:
            continue
        status = entry(om, p.id)[0]
        sig = p.signature()
        if sig in seen and seen[sig][0] != status:
            sys.exit("signature %s has mixed statuses: %s and %s"
                     % (sig, seen[sig][0], status))
        seen.setdefault(sig, (status, []))[1].append(p.id)
    w("  %-11s %-52s %s" % ("status", "endpoint", "probes"))
    for sig, (status, ids) in sorted(seen.items(), key=lambda kv: kv[1][0]):
        w("  %-11s %-52s %s" % (status, sig, ", ".join(ids)))
    w("")
    sig_runnable = sum(1 for st, _ in seen.values() if st in RUNNABLE)
    w("  %d of %d distinct endpoints are expressible through this client." % (
        sig_runnable, len(seen)))
    w("  Counted per probe the figure is %d of %d, which is the same fact" % (
        runnable, len(probes)))
    w("  weighted by how many probes paper 1 happened to point at one endpoint.")
    w("")

    gated = [(p, entry(om, p.id)[4]) for p in probes if entry(om, p.id)[4]]
    if gated:
        # Expressible is not the same as attempted. This client compares the
        # endpoint against what /v1/config declared before sending anything,
        # so paper 1's declaration tier decides what this client will try.
        w("## Gated on what the catalog declared, not on what it serves")
        w("")
        w("  %d of the %d probes above are attempted only if the catalog named"
          % (len(gated), len(probes)))
        w("  the endpoint in the `endpoints` array of its /v1/config. What the")
        w("  gate does when it is closed is not uniform:")
        w("")
        for gate, meaning in GATES.items():
            ids = [p.id for p, g in gated if g == gate]
            if not ids:
                continue
            w("  %-13s %s" % (gate, meaning))
            for line in _wrap(", ".join(ids), width=64):
                w("      %s" % line)
            w("")
        ungated_ids = [p.id for p in probes
                       if entry(om, p.id)[0] in RUNNABLE and not entry(om, p.id)[4]]
        w("  %-13s %s" % ("(no gate)", "sent whatever /v1/config declared"))
        for line in _wrap(", ".join(ungated_ids) or "none", width=64):
            w("      %s" % line)
        w("")

    w("## Notes, per probe that is not a plain `reachable`")
    w("")
    for p in probes:
        status, symbol, ref, note, _gate = entry(om, p.id)
        if status == "reachable" and not note:
            continue
        w("  %s  [%s]" % (p.id, status))
        for line in _wrap(note or "(no note)"):
            w("      %s" % line)
        w("")

    w("## Reached by the client, not probed by paper 1")
    w("")
    for name, symbol, ref, note in om.BEYOND_THE_SWEEP:
        w("  %s  --  %s  (%s)" % (name, symbol, ref))
        for line in _wrap(note):
            w("      %s" % line)
        w("")

    w("## Not verified, and therefore not claimed")
    w("")
    for item in om.UNVERIFIED:
        for line in _wrap(item):
            w("  %s" % line)
        w("")

    with open(out_path, "w") as fh:
        fh.write("\n".join(out).rstrip() + "\n")
    print("wrote %s   %d probes" % (
        os.path.relpath(out_path, HERE), len(probes)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--client", default="rust", choices=sorted(CLIENTS),
                    help="which client's map to render. Default: rust.")
    ap.add_argument("--all", action="store_true",
                    help="render every client's surface.")
    args = ap.parse_args()
    for name in (sorted(CLIENTS) if args.all else [args.client]):
        surface(name)


def _wrap(text, width=68):
    words, line, lines = text.split(), "", []
    for word in words:
        if line and len(line) + 1 + len(word) > width:
            lines.append(line)
            line = word
        else:
            line = "%s %s" % (line, word) if line else word
    if line:
        lines.append(line)
    return lines


if __name__ == "__main__":
    main()
